export const mockOrders = [
  {
    id: "ORD-12345678",
    date: "May 10, 2023",
    documentType: "Birth Certificate",
    sourceLanguage: "Spanish",
    targetLanguage: "English",
    serviceLevel: "Standard",
    status: "completed",
    total: 59.99,
    completedDate: "May 13, 2023",
    estimatedDelivery: "May 15, 2023",
  },
  {
    id: "ORD-23456789",
    date: "May 15, 2023",
    documentType: "Marriage Certificate",
    sourceLanguage: "French",
    targetLanguage: "English",
    serviceLevel: "Expedited",
    status: "processing",
    total: 89.99,
    estimatedDelivery: "May 17, 2023",
  },
  {
    id: "ORD-34567890",
    date: "May 18, 2023",
    documentType: "Diploma",
    sourceLanguage: "German",
    targetLanguage: "English",
    serviceLevel: "Standard",
    status: "pending",
    total: 49.99,
    estimatedDelivery: "May 23, 2023",
  },
  {
    id: "ORD-45678901",
    date: "April 25, 2023",
    documentType: "Legal Contract",
    sourceLanguage: "English",
    targetLanguage: "Chinese",
    serviceLevel: "Certified",
    status: "completed",
    total: 129.99,
    completedDate: "April 30, 2023",
    estimatedDelivery: "May 1, 2023",
  },
  {
    id: "ORD-56789012",
    date: "May 5, 2023",
    documentType: "Medical Records",
    sourceLanguage: "Russian",
    targetLanguage: "English",
    serviceLevel: "Expedited",
    status: "completed",
    total: 99.99,
    completedDate: "May 7, 2023",
    estimatedDelivery: "May 8, 2023",
  },
  {
    id: "ORD-67890123",
    date: "May 20, 2023",
    documentType: "Business Proposal",
    sourceLanguage: "English",
    targetLanguage: "Japanese",
    serviceLevel: "Standard",
    status: "processing",
    total: 79.99,
    estimatedDelivery: "May 25, 2023",
  },
  {
    id: "ORD-78901234",
    date: "May 22, 2023",
    documentType: "Immigration Documents",
    sourceLanguage: "Arabic",
    targetLanguage: "English",
    serviceLevel: "Certified",
    status: "pending",
    total: 149.99,
    estimatedDelivery: "May 27, 2023",
  },
];
