CREATE TABLE public.clio_quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL NOT NULL, -- Link to the user who initiated
    source TEXT DEFAULT 'clio_custom_action' NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL, -- e.g., pending, processing, completed
    clio_subject_id TEXT NULL, -- ID of the Clio Matter or Document
    clio_subject_type TEXT NULL, -- 'matter' or 'document'
    client_name TEXT NULL, -- Client name from Clio Matter
    client_email TEXT NULL, -- Client primary email from Clio Matter
    subject_description TEXT NULL -- Matter description or Document name
    -- Add any other relevant columns you might need
);

-- Add Row Level Security (RLS) - Basic example: only authenticated users can insert their own quotes
ALTER TABLE public.clio_quotes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to insert their own clio_quotes"
ON public.clio_quotes
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Optional: Allow users to read their own quotes (adjust SELECT policy as needed)
-- CREATE POLICY "Allow users to select their own clio_quotes"
-- ON public.clio_quotes
-- FOR SELECT
-- TO authenticated
-- USING (auth.uid() = user_id);

-- Optional: Index on user_id for faster lookups
-- CREATE INDEX idx_clio_quotes_user_id ON public.clio_quotes(user_id);
